source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ContainerEquality_Example', :exclusive => true do
  pod 'ContainerEquality', :path => '../'
end

target 'ContainerEquality_Tests', :exclusive => true do
  pod 'ContainerEquality', :path => '../'

  
end
